// Initialize Icons
lucide.createIcons();

const savedTheme = localStorage.getItem('drishti-theme') || 'dark';
document.body.classList.toggle('light-mode', savedTheme === 'light');
function updateThemeToggle() { const lightMode = document.body.classList.contains('light-mode'); document.getElementById('themeToggle').setAttribute('aria-label', lightMode ? 'Switch to dark mode' : 'Switch to light mode'); document.getElementById('themeToggle').title = lightMode ? 'Switch to dark mode' : 'Switch to light mode'; document.querySelector('.theme-label').textContent = lightMode ? 'Dark' : 'Light'; }
updateThemeToggle();
document.getElementById('themeToggle').addEventListener('click', () => { const lightMode = !document.body.classList.contains('light-mode'); document.body.classList.toggle('light-mode', lightMode); localStorage.setItem('drishti-theme', lightMode ? 'light' : 'dark'); updateThemeToggle(); });

const translations = {
    en: { subtitle: 'AI-Enabled Landslide Early Warning & Lifeline Monitoring Platform', feeds: 'IMD & Satellite Feeds', active: 'ACTIVE', pitch: 'Pitch & Architecture', simulator: 'Interactive Rainfall Hazard Simulator', allNer: 'All NER', criticalOnly: 'Critical Only', blockedRoads: 'Blocked Roads', roadLifelines: 'Road Lifelines', citizenReport: 'Citizen Report', emergencyAlert: 'Emergency Alert' },
    bn: { subtitle: 'AI-চালিত ভূমিধস আগাম সতর্কতা ও জীবনরেখা পর্যবেক্ষণ প্ল্যাটফর্ম', feeds: 'IMD ও স্যাটেলাইট ফিড', active: 'সক্রিয়', pitch: 'উপস্থাপনা ও আর্কিটেকচার', simulator: 'ইন্টার‍্যাক্টিভ বৃষ্টিপাত ঝুঁকি সিমুলেটর', allNer: 'সমগ্র উত্তর-পূর্ব', criticalOnly: 'শুধু সংকটপূর্ণ', blockedRoads: 'অবরুদ্ধ সড়ক', roadLifelines: 'সড়ক জীবনরেখা', citizenReport: 'নাগরিক রিপোর্ট', emergencyAlert: 'জরুরি সতর্কতা' },
    hi: { subtitle: 'AI-सक्षम भूस्खलन पूर्व चेतावनी और जीवनरेखा निगरानी प्लेटफॉर्म', feeds: 'IMD और सैटेलाइट फीड', active: 'सक्रिय', pitch: 'प्रस्तुति और आर्किटेक्चर', simulator: 'इंटरैक्टिव वर्षा जोखिम सिम्युलेटर', allNer: 'पूरा NER', criticalOnly: 'केवल गंभीर', blockedRoads: 'अवरुद्ध सड़कें', roadLifelines: 'सड़क जीवनरेखा', citizenReport: 'नागरिक रिपोर्ट', emergencyAlert: 'आपातकालीन चेतावनी' },
    as: { subtitle: 'AI-ভিত্তিক ভূমিস্খলন আগতীয়া সতৰ্কবাণী আৰু জীৱনৰে’খা নিৰীক্ষণ প্লেটফৰ্ম', feeds: 'IMD আৰু উপগ্ৰহ ফিড', active: 'সক্ৰিয়', pitch: 'উপস্থাপনা আৰু আৰ্হি', simulator: 'ইণ্টাৰেক্টিভ বৰষুণৰ বিপদ ছিমুলেটৰ', allNer: 'সমগ্ৰ উত্তৰ-পূব', criticalOnly: 'কেৱল সংকটপূৰ্ণ', blockedRoads: 'বন্ধ পথ', roadLifelines: 'পথ জীৱনৰে’খা', citizenReport: 'নাগৰিক প্ৰতিবেদন', emergencyAlert: 'জৰুৰী সতৰ্কবাণী' },
    ne: { subtitle: 'AI-सक्षम पहिरो पूर्व चेतावनी तथा जीवनरेखा निगरानी प्लेटफर्म', feeds: 'IMD तथा स्याटेलाइट फिड', active: 'सक्रिय', pitch: 'प्रस्तुति तथा आर्किटेक्चर', simulator: 'अन्तरक्रियात्मक वर्षा जोखिम सिमुलेटर', allNer: 'सम्पूर्ण NER', criticalOnly: 'गम्भीर मात्र', blockedRoads: 'अवरुद्ध सडक', roadLifelines: 'सडक जीवनरेखा', citizenReport: 'नागरिक रिपोर्ट', emergencyAlert: 'आपतकालीन चेतावनी' }
};
document.getElementById('languageSelector').addEventListener('change', event => { const selected = translations[event.target.value] || translations.en; document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = selected[element.dataset.i18n] || translations.en[element.dataset.i18n]; }); });

// Interactive demo data is clearly separated from live API feeds.
const map = L.map('map').setView([26.2006, 92.9376], 7);
const base = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors', className: 'osm-tiles', maxZoom: 19 }).addTo(map);
const riskLayer = L.layerGroup().addTo(map), rainfallLayer = L.layerGroup().addTo(map), roadLayer = L.layerGroup().addTo(map), reportLayer = L.layerGroup().addTo(map);
const slopeLayer = L.layerGroup(), soilLayer = L.layerGroup(), satelliteLayer = L.layerGroup();
const colors = { SAFE: '#22c55e', WATCH: '#eab308', WARNING: '#f97316', CRITICAL: '#ef4444' };
const risks = [
    { name: 'Gangtok, Sikkim', pos: [27.3389, 88.6065], score: 82, rain: 96, slope: 34, soil: 81, probability: 78, window: '12–24 hours' },
    { name: 'Darjeeling, West Bengal', pos: [27.041, 88.2663], score: 74, rain: 88, slope: 31, soil: 76, probability: 69, window: '6–12 hours' },
    { name: 'Kohima, Nagaland', pos: [25.6751, 94.1086], score: 58, rain: 62, slope: 27, soil: 64, probability: 48, window: '24–48 hours' },
    { name: 'Aizawl, Mizoram', pos: [23.7271, 92.7176], score: 43, rain: 49, slope: 22, soil: 55, probability: 34, window: '48 hours' },
    { name: 'Shillong, Meghalaya', pos: [25.5788, 91.8933], score: 27, rain: 35, slope: 17, soil: 42, probability: 18, window: 'Low risk' },
    { name: 'Tawang, Arunachal Pradesh', pos: [27.586, 91.86], score: 66, rain: 71, slope: 29, soil: 68, probability: 57, window: '24 hours' }
];
const level = score => score <= 30 ? 'SAFE' : score <= 50 ? 'WATCH' : score <= 70 ? 'WARNING' : 'CRITICAL';
const popup = item => `<div style="min-width:190px"><b>${item.name}</b><br><span style="color:${colors[level(item.score)]}">${level(item.score)} · ${item.score}/100</span><hr>Rainfall: ${item.rain} mm/24h<br>Slope: ${item.slope}°<br>Soil Moisture: ${item.soil}%<br>Landslide Probability: ${item.probability}%<br>Prediction: ${item.score > 50 ? 'HIGH RISK' : 'MONITOR'}<br>Expected Window: ${item.window}<br><small>DEMO DATA · Updated 5 min ago</small></div>`;
function selectRisk(item) {
    const risk = level(item.score), color = colors[risk];
    document.getElementById('riskScore').textContent = item.score; document.getElementById('riskLevel').textContent = risk;
    document.getElementById('riskLevel').style.color = color; document.getElementById('riskGauge').style.width = item.score + '%'; document.getElementById('riskGauge').style.background = color;
    ['Rain', 'Slope', 'Soil', 'Probability', 'Window'].forEach((key, index) => document.getElementById('risk' + key).textContent = [item.rain + ' mm', item.slope + '°', item.soil + '%', item.probability + '%', item.window][index]);
    document.getElementById('riskPrediction').textContent = item.score > 50 ? 'HIGH RISK' : 'MONITOR'; document.getElementById('riskPrediction').style.color = color;
}
risks.forEach(item => { const risk = level(item.score); const marker = L.circleMarker(item.pos, { radius: 9, fillColor: colors[risk], color: '#fff', weight: 2, fillOpacity: .9 }); marker.addTo(riskLayer).bindPopup(popup(item)); marker.on('click', () => selectRisk(item)); L.circle(item.pos, { radius: item.score * 75, color: colors[risk], weight: 1, fillOpacity: .08 }).addTo(riskLayer); L.circle(item.pos, { radius: item.rain * 500, color: '#38bdf8', weight: 1, opacity: .18, fillOpacity: 0 }).addTo(rainfallLayer); });
const roads = [{ name: 'NH-10 — Siliguri–Gangtok', coords: [[26.9,88.3],[27.04,88.45],[27.34,88.61]], status: 'BLOCKED', risk: 'HIGH', color: '#ef4444', blockage: '29th Mile', alternative: 'Lava–Algarah–Reshi Road' }, { name: 'NH-29 — Dimapur–Kohima', coords: [[25.88,93.72],[25.68,94.11]], status: 'PARTIAL', risk: 'MODERATE', color: '#f59e0b', blockage: 'Dzüdza Section', alternative: 'Jotsoma Bypass' }, { name: 'NH-06 — Silchar–Imphal', coords: [[24.82,92.8],[24.75,93.95]], status: 'OPEN', risk: 'LOW', color: '#22c55e', blockage: 'None', alternative: 'None required' }];
const roadLines = roads.map(road => L.polyline(road.coords, { color: road.color, weight: 5, opacity: .9 }).addTo(roadLayer).bindPopup(`<b>${road.name}</b><br>Status: ${road.status}<br>Risk: ${road.risk}<br>Blockage: ${road.blockage}<br>Alternative: ${road.alternative}<br><small>DEMO STATUS</small>`));
L.polyline([[27.04,88.45],[27.16,88.62],[27.12,88.75],[27.05,88.83]], { color: '#38bdf8', weight: 3, dashArray: '8 7', opacity: .9 }).addTo(roadLayer).bindPopup('<b>NH-10 Detour Route</b><br>Lava – Algarah – Reshi Road<br><small>DEMO ROUTE</small>');
const demoReports = [{ pos: [27.31,88.63], title: 'Road crack', location: 'Gangtok • NH-10', time: '8 min ago', severity: 'HIGH' }, { pos: [25.61,91.92], title: 'Landslide debris', location: 'Shillong • Mawlai', time: '16 min ago', severity: 'MODERATE' }, { pos: [25.69,94.13], title: 'Fallen rocks', location: 'Kohima • NH-29', time: '24 min ago', severity: 'HIGH' }];
const reportMarkers = demoReports.map((report, index) => L.marker(report.pos).addTo(reportLayer).bindPopup(`<b>Citizen Report CR-${120 + index}</b><br>${report.title}<br>AI verification: <span style="color:#22c55e">VALID</span><br><small>DEMO DATA · Reported today</small>`));
document.getElementById('citizenReports').innerHTML = demoReports.map(report => `<div class="citizen-report"><div class="flex items-center justify-between gap-1"><span class="report-dot report-${report.severity.toLowerCase()}"></span><b>${report.title}</b><span class="text-[9px] text-gray-500">${report.time}</span></div><p class="text-[10px] text-gray-400 mt-1">${report.location}</p><span class="text-[9px] ${report.severity === 'HIGH' ? 'text-red-300' : 'text-orange-300'}">${report.severity} · VALIDATED</span></div>`).join('');
L.control.layers({ 'Dark base map': base }, { 'Landslide Risk': riskLayer, 'Rainfall': rainfallLayer, 'Road Status': roadLayer, 'Slope / Elevation': slopeLayer, 'Soil Moisture': soilLayer, 'Citizen Reports': reportLayer, 'Satellite / Terrain': satelliteLayer }, { collapsed: false }).addTo(map);
const legend = L.control({ position: 'bottomleft' }); legend.onAdd = () => { const div = L.DomUtil.create('div', 'map-legend'); div.innerHTML = `<b>RISK & LIFELINE KEY</b><br><span class="legend-dot" style="background:#22c55e"></span>Safe &nbsp; <span class="legend-dot" style="background:#eab308"></span>Moderate<br><span class="legend-dot" style="background:#f97316"></span>High Risk &nbsp; <span class="legend-dot" style="background:#ef4444"></span>Critical<br><span class="legend-line" style="border-color:#22c55e"></span>Open Road<br><span class="legend-line" style="border-color:#f59e0b"></span>Risky Road<br><span class="legend-line" style="border-color:#ef4444"></span>Blocked Road<br>📍 Citizen Report`; return div; }; legend.addTo(map);
const forecast = [42, 54, 68, 91, 124], chartX = [20, 135, 250, 365, 480], chartPoints = forecast.map((value, index) => `${chartX[index]},${95 - (value / 124 * 70)}`).join(' '); document.getElementById('forecastLine').setAttribute('points', chartPoints); document.getElementById('forecastPoints').innerHTML = forecast.map((value, index) => `<circle cx="${chartX[index]}" cy="${95 - (value / 124 * 70)}" r="4" fill="#38bdf8" stroke="#0f172a" stroke-width="2"><title>${value} mm</title></circle>`).join(''); document.getElementById('forecastLabels').innerHTML = forecast.map((value, index) => `<text x="${chartX[index]}" y="108" fill="#94a3b8" font-size="11" text-anchor="middle">${['Now', '+3h', '+6h', '+12h', '+24h'][index]}</text>`).join('');
const slider = document.getElementById('rainfallSlider'), display = document.getElementById('rainfallVal'); function updateSimulator(event) { const rain = Number(event.target.value), slope = 34, soil = Math.min(100, 45 + Math.round(rain / 3)), score = Math.min(100, Math.round(.5 * rain + .35 * slope + .15 * soil)), risk = level(score), color = colors[risk]; display.textContent = rain + ' mm'; document.getElementById('simRiskTier').lastChild.textContent = ' ' + (risk === 'CRITICAL' ? 'CRITICAL ALERT' : risk === 'WARNING' ? 'HIGH WARNING' : risk === 'WATCH' ? 'ADVISORY WATCH' : 'SAFE'); document.getElementById('simRiskDot').style.background = color; document.getElementById('simRiskTier').style.color = color; document.getElementById('simRiskScore').textContent = '(' + score + '/100)'; selectRisk({ name: 'Rainfall simulation zone', score, rain, slope, soil, probability: Math.max(5, score - 4), window: score > 70 ? '12–24 hours' : '48 hours' }); } slider.addEventListener('input', updateSimulator); document.getElementById('resetSimulator').addEventListener('click', () => { slider.value = 45; updateSimulator({ target: slider }); });
const riskMarkers = [...riskLayer.getLayers()].filter(layer => layer instanceof L.CircleMarker); document.querySelectorAll('.map-filter').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.map-filter').forEach(item => item.classList.remove('bg-emerald-600')); button.classList.add('bg-emerald-600'); const filter = button.dataset.filter; riskMarkers.forEach(marker => marker.setStyle({ opacity: filter === 'blocked' ? 0 : filter === 'critical' && marker.options.fillColor !== colors.CRITICAL ? 0 : 1, fillOpacity: filter === 'blocked' ? 0 : filter === 'critical' && marker.options.fillColor !== colors.CRITICAL ? 0 : .9 })); if (filter === 'blocked') map.addLayer(roadLayer); }));
document.querySelectorAll('.road-focus').forEach(button => button.addEventListener('click', () => { const line = roadLines[Number(button.dataset.roadFocus)]; map.fitBounds(line.getBounds(), { padding: [30, 30] }); line.openPopup(); }));
const incidentTargets = [{ road: 0 }, { road: 1 }, { road: 2 }, { marker: 0 }];
function focusIncident(index) { const target = incidentTargets[index]; document.querySelectorAll('.incident-card').forEach(card => card.classList.remove('selected')); document.querySelector(`[data-incident="${index}"]`).classList.add('selected'); if (target.road !== undefined) { const line = roadLines[target.road]; map.fitBounds(line.getBounds(), { padding: [30, 30] }); line.openPopup(); } else { map.setView(demoReports[target.marker].pos, 9); reportMarkers[target.marker].openPopup(); } }
document.querySelectorAll('.incident-card').forEach(card => card.addEventListener('click', () => focusIncident(Number(card.dataset.incident))));
document.getElementById('viewRoute').addEventListener('click', () => { const line = roadLines[0]; map.fitBounds(line.getBounds(), { padding: [30, 30] }); line.openPopup(); showIncidentToast('Alternate route highlighted on the map.'); });
function showIncidentToast(message) { const toast = document.getElementById('incidentToast'); toast.textContent = message; toast.classList.add('visible'); window.setTimeout(() => toast.classList.remove('visible'), 2400); }
document.querySelectorAll('[data-demo-action]').forEach(button => button.addEventListener('click', () => showIncidentToast(button.dataset.demoAction + ' queued for demonstration only.')));
const regionData = { Gangtok: risks[0], Darjeeling: risks[1], Shillong: risks[4], Kohima: risks[2], Aizawl: risks[3], Itanagar: { name: 'Itanagar, Arunachal Pradesh', pos: [27.0844, 93.6053], score: 61, rain: 74, slope: 28, soil: 69, probability: 53, window: '24 hours' }, Guwahati: { name: 'Guwahati, Assam', pos: [26.1445, 91.7362], score: 35, rain: 41, slope: 14, soil: 48, probability: 24, window: '48 hours' } }; document.getElementById('regionSelector').addEventListener('change', event => { const item = regionData[event.target.value]; selectRisk(item); map.flyTo(item.pos, 9, { duration: .8 }); });
const timeline = [82, 78, 71, 64]; document.getElementById('timelineValues').innerHTML = timeline.map(value => `<span>${value}</span>`).join('');
document.querySelectorAll('.tab-button').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.tab-button').forEach(item => item.classList.remove('bg-emerald-600')); document.querySelectorAll('.tab-view').forEach(item => item.classList.remove('active')); button.classList.add('bg-emerald-600'); document.getElementById(button.dataset.tab).classList.add('active'); }));
const navTargets = { dashboard: '.dashboard-grid', map: '#map', risk: '#riskPanel', incidents: '#incidentCenter', response: '#incidentCenter', reports: '#reports', alerts: '#alerts' };
document.querySelectorAll('.top-nav-item, .top-nav-alert').forEach(button => button.addEventListener('click', () => { const target = navTargets[button.dataset.nav]; if (!target) return; if (button.dataset.nav === 'reports' || button.dataset.nav === 'alerts') document.querySelector(`[data-tab="${button.dataset.nav}"]`).click(); document.querySelectorAll('.top-nav-item, .top-nav-alert').forEach(item => { item.classList.toggle('active', item === button); item.removeAttribute('aria-current'); }); if (button.classList.contains('top-nav-item')) button.setAttribute('aria-current', 'page'); document.querySelector(target).scrollIntoView({ behavior: 'smooth', block: 'start' }); }));
document.getElementById('submitReport').addEventListener('click', () => { const location = document.getElementById('reportLocation').value.trim() || 'Unspecified NER location'; const description = document.getElementById('reportDescription').value.trim() || 'Hazard report submitted by citizen'; const item = { name: location, pos: [26.5 + (Math.random() - .5) * 2, 92.5 + (Math.random() - .5) * 3], score: 62, rain: 0, slope: 0, soil: 0, probability: 0, window: 'Pending review' }; L.marker(item.pos).addTo(reportLayer).bindPopup(`<b>Report ID: DR-${Date.now().toString().slice(-5)}</b><br>Location: ${location}<br>${description}<br>AI result: Valid Landslide Report<br><small>DEMO AI VERIFICATION · Just now</small>`); document.getElementById('reportResult').textContent = '✓ Valid Landslide Report · DEMO AI VERIFICATION'; document.getElementById('reportResult').classList.remove('hidden'); });
document.querySelectorAll('.alert-demo').forEach(button => button.addEventListener('click', () => document.getElementById('alertStatus').textContent = button.textContent + ' queued for demonstration only. No external message was sent.'));